AUT1.2 (#2)
* artificial delays

* further

* small fix

* GH workflow fix

* GH - reachability for webpages

diff --git a/.github/workflows/playwright-tests.yml b/.github/workflows/playwright-tests.yml
--- a/.github/workflows/playwright-tests.yml
+++ b/.github/workflows/playwright-tests.yml
@@ -31,8 +31,24 @@ jobs:
       - name: Install Playwright browser
         run: python -m playwright install --with-deps ${{ matrix.browser }}
 
+      - name: Check reachability of the site under test
+        run: |
+          for url in \
+            https://the-internet.herokuapp.com/login \
+            https://the-internet.herokuapp.com/js/vendor/298279967.js \
+            https://the-internet.herokuapp.com/js/vendor/jquery-1.11.3.min.js \
+            https://the-internet.herokuapp.com/js/vendor/jquery-ui-1.11.4/jquery-ui.js \
+            https://the-internet.herokuapp.com/js/foundation/foundation.js \
+            https://the-internet.herokuapp.com/css/app.css \
+            https://log.optimizely.com/ \
+            https://rum.optimizely.com/; do
+            curl -s -o /dev/null --max-time 40 \
+              -w "HTTP %{http_code}  dns %{time_namelookup}s  connect %{time_connect}s  total %{time_total}s  $url\n" "$url" \
+              || echo "FAILED (curl exit $?)  $url"
+          done
+
       - name: Run tests
-        run: pytest --browser ${{ matrix.browser }} --reruns 2 --junitxml=reports/junit-${{ matrix.browser }}.xml
+        run: python -m pytest -m smoke --browser ${{ matrix.browser }} --junitxml=reports/junit-${{ matrix.browser }}.xml
 
       - name: Upload test artifacts
         if: ${{ !cancelled() }}
